# General input/ouput info
frames: 256
num_classes: 11
img_size: 224
spatial_frozen: False

# Temporal Transformer
temporal_type: longformer
temporal_args:
  dim: 384
  depth: 3
  heads: 12
  dim_head: 128
  mlp_dim: 3072
  attention_window: 8
  attention_mode: sliding_chunks
  emb_dropout: 0.3
  dropout: 0.3
  pool: cls