# Full-SimStepNet
# General input/ouput info
frames: 256
num_classes: 17
img_size: 224
spatial_frozen: False
ckpt_dir : None

# Spatial Transformer
spatial_args:
  hidden: 128
  channels: 3
  second_head_input: 128
  model: 'vit_small_patch16_224.augreg_in21k_ft_in1k'
  weights_dir: '/shared/nl011006/res_ds_ml_restricted/shaohung/train_log/runs_MECCANO/stage1_log/train_KFA_no_bg/checkpoints/best.pth'

temporal_args:
  frames: 256