
# General input/ouput info
frames: 32
num_classes: 11 
img_size: 224
spatial_frozen: False
ckpt_dir : None

# Spatial Transformer
spatial_args:
  hidden: 384
  channels: 3
  second_head_input: 128
  model: 'vit_small_patch16_224.augreg_in21k_ft_in1k'
  weights_dir: 'YOUR OWN PT WEIGHTS DIR'

# Temporal Transformer
temporal_type: transformer
temporal_args:
  dim: 384
  depth: 3
  heads: 4
  dim_head: 128
  mlp_dim: 4096
  dropout: 0.1