# General input/ouput info
frames: 256
num_classes: 17
img_size: 224
spatial_frozen: False
ckpt_dir : None

# Spatial Transformer
spatial_args:
  hidden: 128
  channels: 3
  second_head_input: 128
  model: 'vit_small_patch16_224.augreg_in21k_ft_in1k'
  weights_dir: 'YOUR OWN PT WEIGHTS DIR'
temporal_args:
  frames: 256